name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        uses: FarasAtNobel/buildozer-action@master
        with:
          buildozer_version: master
          command: android debug
          repository_root: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SoccerStars-AI-Helper
          path: bin/*.apk
